server:
  port: 7071
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5500/DriverDB
    username: postgres
    password: asd123asd
  jpa:
    hibernate:
      ddl-auto: update